### ISSUE TITLE
Exception warning

### ISSUE THREAD

**Issue by AlessandroLacroce** [Appboy/appboy-unity-sdk#20]
We get this warning on some Android devices (Samsung Galaxy S6, LG Nexus 5x for example):

*I/Appboy v1.10.3 .bo.app.x(893): Adding request to dispatcher with parameters: {"only_respond_with":[]}
W/Appboy v1.10.3 .bo.app.di(893): Experienced exception processing API response. Failing task.
W/Appboy v1.10.3 .bo.app.di(893): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.i.b(SourceFile:131)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.i.a(SourceFile:69)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.i.a(SourceFile:51)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.i.a(SourceFile:42)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.l.a(SourceFile:36)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.k.a(SourceFile:36)
W/Appboy v1.10.3 .bo.app.di(893): 	at bo.app.di.run(SourceFile:60)
W/Appboy v1.10.3 .bo.app.di(893): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/Appboy v1.10.3 .bo.app.di(893): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/Appboy v1.10.3 .bo.app.di(893): 	at java.lang.Thread.run(Thread.java:818)
*

We get it once every 2/3 sec.

**Comment by briancaw** [comment]
Hi @AlessandroLacroce 

Is this crashing the app or just showing up in the logcat?  This failure indicates that we were unable to connect to our servers, so it should be a harmless failure and it'll just retry (it usually just means there's no network connection).  

The only thing a bit worrisome here is that you're seeing it every 2/3 seconds instead of every 10-15 seconds.  Have you modified your dispatch frequency at all (via appboy.xml)?

If you can reproduce this condition when you are certain you have internet and there are no network conditions that might cause a failure, please let us know.  Is your app logging data to our dashboard?  Any functional issues you're seeing in parallel with this would be god to know.

Thanks,
Brian

**Comment by AlessandroLacroce** [comment]
I confirm that the log is sent every 2/3 second and the device has network connectivity. We had to implement REST API to log data into your dashboard.

**Comment by briancaw** [comment]
Hi @AlessandroLacroce 

It sounds like your application is not communicating with our servers correctly - you definitely should not be having to use the REST API to log data.  Have you ensured your API key is correct?  Can you let us know what fields you have set in your appboy.xml file and what permissions you have in your AndroidManifest.xml?  Is it possible you are testing behind a firewall or have any other unusual network conditions?

Thanks,
Brian

**Comment by briancaw** [comment]
Hey @AlessandroLacroce 

I'm closing this issue for now.  Please reopen if you're still having issues.

Thanks,
Brian
