### ISSUE TITLE
Android Status Bar is visible during Appboy In-App Message

### ISSUE THREAD

**Issue by Will5** [Appboy/appboy-unity-sdk#26]
On both Android an iOS, we are full screen; no status bar. However, during an Appboy In-App Message on Android, the status bar is visible. Is there a way we can disable that, so that appboy matches the experience of the rest of the app? Maybe a setting to enable or disable the status bar?

**Comment by Bucimis** [comment]
Hi @Will5,

Thanks for this feedback!  We have a solution in the works.  We will notify you again when its ready - our expected timeline is sometime in Q4.  Let us know if that works for you.

Thanks,
Jared

**Comment by Will5** [comment]
Thanks, is this in 1.12.0?

**Comment by Bucimis** [comment]
Hi @Will5,

Thanks for following up. We didn't add first-class support in the current release due to technical limitations of the solutions we were exploring. Our apologies for not following up sooner.

Note that we did expose the `Appboy.Theme.Transparent` style (see https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-unity/res/values/styles.xml), which styles our IAM activities. You may use custom Android attributes or extend an existing Android no-status-bar theme to style the in-app message activity to your liking (see https://www.braze.com/documentation/Android/#custom-styling for more on overriding styles).

We'll continue to investigate potential solutions on our end as well.

Thanks again,
Jared

**Comment by Bucimis** [comment]
Hi @Will5, a long time coming, but the status bar is now invisible by default on Android in-app messages in our latest release 1.16.0.
