### ISSUE TITLE
Appboy Security Update: TLS 1.0/1.1 Deprecation Plan Announcement

### ISSUE THREAD

**Issue by Will5** [Appboy/appboy-unity-sdk#27]
According to the Appboy Security Update: TLS 1.0/1.1 Deprecation Plan Announcement, Android must update to Appboy SDK version 2.0.3 by May 31, 2018. That's still a long way off, but I notice the Appboy Unity SDK is only up to Appboy SDK version 2.0.0. What is the release plan for an updated Appboy Unity SDK?

> Apple devices will not be affected by Appboy’s planned deprecation because Apple has required TLS 1.2 since the end of 2016. The same is true of modern web browsers, so we do not anticipate that these changes will have any impact on Web SDK usage. However, Android devices running Android 4.4 (KitKat) or lower may not use TLS 1.2 by default, so please take steps to upgrade any of your Android integrations to at least Appboy SDK version 2.0.3 (which uses TLS 1.2 by default, if a given device can support it) by May 31, 2018.

**Comment by Bucimis** [comment]
Hi @Will5 

Apologies for the late response.  The next Appboy Unity SDK release will contain TLS 1.2 compatible aars and will be released well in advance of the TLS deadline.  Note that this release will be for Unity 2017.

For your reference, it's possible to update to any Appboy Android SDK version generally by downloading our `base` and `ui` project `aar` files for Android and dropping them directly in your `Assets/Plugins/Android/libs` folder.

They should replace the files called `appboy-ui.aar` and `appboy.aar` already present in the `libs` folder.

base `aar`:
https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/sdk/com/appboy/android-sdk-base/2.1.4
ui `aar`:
https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/sdk/com/appboy/android-sdk-ui/2.1.4

By using this method, you can add TLS support at any time.  However, due to its manual nature, we'd recommend waiting for the fix.

Thanks,
Jared

**Comment by Will5** [comment]
Thanks, is this in 1.12.0?

**Comment by Bucimis** [comment]
@Will5 yep, TLS 1.2 support for android is included in Braze Unity SDK 1.12.0. Thanks for following up.

**Comment by Bucimis** [comment]
@Will5 closing this now, let us know if you have further followups
