### ISSUE TITLE
IOS Post Process step help

### ISSUE THREAD

**Issue by iliaga** [Appboy/appboy-unity-sdk#45]
hey,  

Trying to enable rich notifications on ios has been successful with a manual approach by adding a notification service as suggested here #39   

now I am trying to integrate it with a post process build using the files that worked for me in the manual approach.
* basing my work on [this post](https://answers.unity.com/questions/1407184/create-notification-service-extension-from-post-bu.html)
* and later added a step to add entitelment. [as seen here](https://forum.unity.com/threads/how-to-put-ios-entitlements-file-in-a-unity-project.442277/)  

I Encounter many issues with automating this process.
some issues encountered are Cycle depedencies between targets, and a linker error.
funny thing is that it doesnt happen when doing this step manually.

**Comment by Bucimis** [comment]
Hi @iliaga, what are the downsides of sticking with the manual approach? Unfortunately it will be difficult for us to consult on using a post-build script to generate a NotificationService as that's beyond the scope of our SDK code.

**Comment by iliaga** [comment]
the downside is a great difficulty to introduce it into automated build systems...
plus its really clunky to do all these steps just to release your app for tests/release **every time:**
1. do some xcode stuff
2. copy paste code 
3. change the targeted platforms
4. press build.
5. wait
6. upload to test flight/ adhoc stuff

IMO its a critical piece of being fully integrated with unity.
Something I hope the great team at braze wants for its users

**Comment by iliaga** [comment]
any decision on the matter? @Bucimis

**Comment by Bucimis** [comment]
Hi @iliaga, we'd recommend the same approach suggested in those posts, namely 1) Storing iOS native files for your extension in a directory in your project (including your notification service source code, Info.plist, and entitlements) 2) Configuring your project using a post-build step (things like linking the UserNotifications framework). In general, I would look to simplify the examples in those posts as much as possible until you have a working solution (for example, most Info.plist fields can be hardcoded initially).

You can also compare your Unity-generated output project structure and configuration (e.g. the PList, signing config, build settings) with that of the working XCode project.

We unfortunately can't provide specific advice beyond these general ideas because this is outside the realm of the Braze SDK. 

Closing for now but feel free to reach out again if you run into specific issues and we'll help if we're able and as appropriate. Let us know how it goes!
