### ISSUE TITLE
iOS seems to be not initializing 2.7.0 Xcode 12 

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-unity-sdk#78]
Updating to 2.7.0 and using Xcode 12 we started having this message and seems not to work

     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **      before Braze was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************

Do we need to call any initialization method from Unity for iOS? Documentation seems to be outdated and it does not say anything

**Comment by MartinGonzalez** [comment]
Found it, we were using a custom AppDelegaterListener where we have AppBoyDeletegate code.
It would be fantastic that appboy provide the Listener instead of AppDelegate to avoid IMPL collisions.

**Comment by patrickkulling** [comment]
Hey Martin.
We are having the same issue.

Can you elaborate on your solution?

Best
Patrick

**Comment by MartinGonzalez** [comment]
Appboy tries to override UnityAppController, if you are using a DelegateListener to call Appboy code remember to comment
IMPL_APP_CONTROLLER_SUBCLASS or remove AppboyAppController class

**Comment by patrickkulling** [comment]
I see. We are not using our own delegate and rely on the fact that Braze/Appboy should start with their AppboyAppController instance. However this seems to be broken on our side since we upgraded to XCode 12.

We might try implementing a custom DelegateListener as well. Thanks!

**Comment by MartinGonzalez** [comment]
I'm not an iOS developer but something similar happens on Android when plugins want to override Activity. We've create an ActivityListener mother that delegates app life cycle to listeners. [Here repo](https://github.com/MartinGonzalez/UnityPlayerActivityListener)

I was trying to understand if this can be done in iOS, but I really hate objective-c xD. Also its possible to create something today with listeners in Unity ios but Unity has old methods and they are not updating them

**Comment by patrickkulling** [comment]
Our issue was actually that there was another 3rd party SDK in our codebase that also defined the `IMPL_APP_CONTROLLER_SUBCLASS` macro. We have not noticed that before, but apparently once you have more than one the final xcode build is no longer deterministic and switches between both macros.

**Comment by Bucimis** [comment]
Thanks everyone for the discussion! 

1) On iOS, as folks have reported, the default automatic integration uses `IMPL_APP_CONTROLLER_SUBCLASS`, which you can only have one of in Unity and which will cause broken behavior if multiple plugins try to define. Our current recommended workaround is to implement Braze logic manually in a global AppDelegate. When doing that, we recommend following the native iOS instructions here https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/ since our automatic integration is just a wrapper around it. We're currently planning to build a swizzling-based solution that avoids the `IMPL_APP_CONTROLLER_SUBCLASS` issue in the future. We'd appreciate any other alternative ideas and feature requests as well!

2)  Yep, on Android, there's a similar issue since multiple inheritance of plugin UnityPlayerActivity subclasses isn't possible. Our UnityPlayerActivity subclass calls methods in this class https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-unity/src/main/java/com/appboy/unity/AppboyUnityActivityWrapper.java directly from its Android lifecycle methods. As an alternative to using our UnityPlayerActivity subclass, you can call these methods directly from your own UnityPlayerActivity subclass or from a `ActivityLifecycleCallbacks` instance.

**Comment by canyousayyes** [comment]
@Bucimis Our project hits the same problem where Braze and another framework both uses `IMPL_APP_CONTROLLER_SUBCLASS`. Similar problem happens in the Android build as well.

For the workaround you suggested, do you have more detail guides on how to implement the Braze logic manually in a global AppDelegate? We're using the Unity Cloud Build so the process of manually inserting some codes after exporting a Xcode project isn't viable.

By the way, is it possible to expose the initialization methods like `startWithApiKey` and `registerForRemoteNotificationsWithProvisional` to the Unity `AppboyBinding` class?

While it will make the developer responsible for initializing the Braze SDK correctly, it also avoid many potential conflicts with other libraries.

**Comment by Bucimis** [comment]
@canyousayyes I agree that a manual delegate integration using only C# is an interesting feature request, I've added that as a feature request.

In the meantime, for implementing manually via your global appdelegate, you should add all calls to `AppboyUnityManager` from https://github.com/Appboy/appboy-unity-sdk/blob/38bf75dbb35851a605fc85751ecf17f6a5585a44/Assets/Plugins/iOS/AppboyAppDelegate.mm#L17, as well as `startWithApiKey`. You can generally skip the logic that reads from the PList, but doing so will cause your in-IDE Unity<>Braze configuration editor to stop working.

Let us know how this sounds, apologies that the workaround is so complex.

**Comment by canyousayyes** [comment]
@Bucimis Thank you. We ended up to use method swizzling to integrate all 3 methods under AppboyAppDeletegate, with the reference of this stackoverflow answer: https://stackoverflow.com/questions/42508476/can-you-have-more-than-one-subclass-of-unityappcontroller

**Comment by Bucimis** [comment]
@canyousayyes good stuff! let us know if anything else comes up
