### ISSUE TITLE
Android Integration Guide braze.xml

### ISSUE THREAD

**Issue by idamaeng** [Appboy/appboy-unity-sdk#81]
Unity Version: 2019.4.10f1
Braze SDK Version: 2.8.0

The Android Integration Guide describes how to configure braze utilising braze.xml, if you name the xml file this way, the plugin throws multiple exceptions, because it is not able to find the xml file.
It only works if you name the xml file appboy.xml. Please fix your documentation.

**Comment by radixdev** [comment]
1. Can you list those exceptions you're seeing?
2. Can you list reproduction steps?
3. Can you post your Braze unity configuration and whether you're using automatic configuration?
4. Can you post the contents of your manually created `braze.xml` file?

Neither the plugin nor the native SDK actually look for a file called `appboy.xml` since AAPT extracts the contents of the `appboy.xml`, `braze.xml`, or [`appboy-generated.xml`](https://github.com/Appboy/appboy-unity-sdk/blob/6f5e3484b7a39178252a9ae5d09f468ed0f4da0c/Assets/Plugins/Appboy/Editor/PreBuild.cs#L13) file into a centralized `strings.xml` file in the built APK. What might be happening is a key namespace collision in that combined `strings.xml` but we'll need more information to be certain.

**Comment by idamaeng** [comment]
I think that I fixed my issue. By accident I put the braze.xml file into the Assets/Plugins/Android/res folder. The correct path should be Assets/Plugins/Android/res/values folder (like you guys mentioned in your documentation). Because the exception messages described that appboy.xml could not be found, I thought that this was the issue.

Sorry for the inconvenience, and have a nice weekend

**Comment by idamaeng** [comment]
At least I have a question regarding the braze.xml file. Can it be used to set up the iOS part of the plugin too?

**Comment by radixdev** [comment]
Happy to help! iOS has its own automatic configuration, also located in the same Braze configuration window as the Android setup. Since iOS uses `plist` files, that xml configuration file can't be used for it.
